version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exstore_server_dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
